version: '2.1'

services:
  vue-ion-skeleton:
    image: vue-ion-skeleton
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js